"""Partial encryption functionality for envdrift.

This module implements a simple build pattern for partial encryption:
- Source files: .env.{env}.clear + .env.{env}.secret
- Generated file: .env.{env} (combined with warning header)
"""

from __future__ import annotations

import logging
import subprocess  # nosec B404
from pathlib import Path
from typing import NamedTuple

from envdrift.config import PartialEncryptionEnvironmentConfig
from envdrift.integrations.dotenvx import DotenvxError, DotenvxWrapper

logger = logging.getLogger(__name__)

# dotenvx stores private keys in this file. It must never be encrypted/decrypted
# as a secret — doing so would lock away the keys needed to decrypt everything else.
_KEYS_FILENAME = ".env.keys"

# Minimum inner width of the warning box. Long file paths expand the box beyond
# this so the right-hand border always stays aligned (see _build_warning_header).
_WARNING_BOX_MIN_WIDTH = 50

# dotenvx writes a public-key assignment into encrypted files. It is not a
# secret (public keys are public) so it must not be counted as a secret var.
_DOTENVX_PUBLIC_KEY_PREFIX = "DOTENV_PUBLIC_KEY"


def _build_warning_header(clear_file: str, secret_file: str) -> str:
    """Build the auto-generated-file warning box, sized to fit its content.

    The right-hand ``/`` border stays aligned regardless of how long the
    ``clear_file`` / ``secret_file`` paths are, because the box width grows to
    fit the longest line instead of using a fixed pad.
    """
    body = [
        "WARNING: AUTO-GENERATED FILE",
        "DO NOT EDIT THIS FILE DIRECTLY",
        "",
        "This file is generated by: envdrift push",
        "",
        "To make changes:",
        "  1. Run:  envdrift pull-partial (decrypts the .secret file)",
        f"  2. Edit: {clear_file}",
        f"  3. Edit: {secret_file}",
        "  4. Run:  envdrift push (re-encrypts .secret and regenerates this)",
    ]
    # Inner width includes the single leading space after "#/", hence +1.
    inner = max(_WARNING_BOX_MIN_WIDTH, max(len(line) for line in body) + 1)
    border = "#/" + "-" * inner + "/"
    lines = [border]
    lines.extend("#/ " + line.ljust(inner - 1) + "/" for line in body)
    lines.append(border)
    return "\n".join(lines) + "\n"


def _is_secret_var_line(line: str) -> bool:
    """Return True if ``line`` is a real secret variable assignment.

    Excludes comments and dotenvx's ``DOTENV_PUBLIC_KEY_*`` artifact so the
    reported secret-var count reflects only the actual secrets.
    """
    stripped = line.strip()
    if "=" not in stripped or stripped.startswith("#"):
        return False
    return not stripped.startswith(_DOTENVX_PUBLIC_KEY_PREFIX)


class PartialEncryptionError(Exception):
    """Partial encryption operation failed."""

    @classmethod
    def encrypt_failed(cls, path: Path, cause: Exception) -> PartialEncryptionError:
        """Create error for encryption failure."""
        return cls(f"Failed to encrypt {path}: {cause}")

    @classmethod
    def decrypt_failed(cls, path: Path, cause: Exception) -> PartialEncryptionError:
        """Create error for decryption failure."""
        return cls(f"Failed to decrypt {path}: {cause}")

    @classmethod
    def file_not_found(cls, path: Path) -> PartialEncryptionError:
        """Create error for missing file."""
        return cls(f"Secret file not found: {path}")


def is_file_encrypted(file_path: Path) -> bool:
    """
    Check if a file contains dotenvx encrypted content.

    Args:
        file_path: Path to check

    Returns:
        True if file contains encrypted: prefix or DOTENV_VAULT markers
    """
    if not file_path.exists():
        return False

    content = file_path.read_text()
    return "encrypted:" in content or "DOTENV_VAULT" in content


def combine_files(
    env_config: PartialEncryptionEnvironmentConfig, *, write: bool = True
) -> dict[str, int | bool]:
    """
    Combine clear and encrypted secret files into a single combined file.

    Process:
        1. Read .env.{env}.clear (cleartext vars)
        2. Read .env.{env}.secret (encrypted vars)
        3. Combine with warning header → .env.{env}

    Args:
        env_config: Environment configuration
        write: When True (default) the combined file is written to disk. When
            False this is a dry run that computes the would-be content and
            reports whether it matches the existing combined file, without
            touching disk. Used by ``envdrift push --check``.

    Returns:
        Dict with counts: {"clear_lines": X, "secret_vars": Y, "in_sync": bool}.
        ``in_sync`` reports whether the on-disk combined file already matches the
        freshly-computed content (always True after a real write).

    Raises:
        PartialEncryptionError: If operation fails
    """
    clear_file = Path(env_config.clear_file)
    secret_file = Path(env_config.secret_file)
    combined_file = Path(env_config.combined_file)

    # Read files
    clear_lines = []
    if clear_file.exists():
        clear_lines = clear_file.read_text().splitlines()

    secret_lines = []
    if secret_file.exists():
        secret_lines = secret_file.read_text().splitlines()

    # Build combined content with warning header
    warning = _build_warning_header(env_config.clear_file, env_config.secret_file)

    combined_lines = warning.splitlines()
    combined_lines.append("")

    # Add clear section
    if clear_lines:
        combined_lines.append(f"# From {env_config.clear_file}")
        combined_lines.extend(clear_lines)
        combined_lines.append("")

    # Add encrypted secret section
    if secret_lines:
        # Skip dotenvx header comments from secret file to avoid clutter.
        # The real public-key header is a 4-line block: the border lines start
        # with "#/---" while the two inner comment lines start with "#/ ". Match
        # the whole "#/" block so the inner comments don't leak into the output.
        secret_content = [line for line in secret_lines if not line.strip().startswith("#/")]
        combined_lines.append(f"# From {env_config.secret_file} (encrypted)")
        combined_lines.extend(secret_content)

    new_content = "\n".join(combined_lines) + "\n"

    existing = combined_file.read_text() if combined_file.exists() else None
    in_sync = existing == new_content

    if write:
        combined_file.write_text(new_content)
        in_sync = True

    # Count real secret variables (excludes comments and dotenvx public-key line)
    secret_var_count = sum(1 for line in secret_lines if _is_secret_var_line(line))

    return {
        "clear_lines": len(clear_lines),
        "secret_vars": secret_var_count,
        "in_sync": in_sync,
    }


def _run_git_update_index(flag: str, path: Path) -> bool:
    """Run ``git update-index <flag> <path>`` and report whether it succeeded.

    Returns True only when git exits 0. A non-zero exit (e.g. the file is not
    tracked) is logged as a warning rather than failing silently; git being
    unavailable is logged at debug level. Either way the caller gets False so it
    can avoid claiming protection that was never applied.
    """
    try:
        result = subprocess.run(  # nosec B603, B607
            ["git", "update-index", flag, str(path)],
            capture_output=True,
            timeout=10,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as exc:
        logger.debug("git update-index %s not applied to %s: %s", flag, path, exc)
        return False
    if result.returncode != 0:
        stderr = result.stderr
        if isinstance(stderr, (bytes, bytearray)):
            stderr = stderr.decode(errors="replace")
        logger.warning(
            "git update-index %s failed for %s (exit %s): %s",
            flag,
            path,
            result.returncode,
            (stderr or "").strip(),
        )
        return False
    return True


def _git_skip_worktree(path: Path) -> bool:
    """Mark path as skip-worktree so git ignores local changes while the file is decrypted.

    This prevents `git add .` from staging a plaintext .secret file after pull-partial.
    Best-effort: returns False (and logs) if git is unavailable or the file is not tracked.
    """
    return _run_git_update_index("--skip-worktree", path)


def _git_unskip_worktree(path: Path) -> bool:
    """Unmark path from skip-worktree so git can track the re-encrypted version.

    Called after encrypt_secret_file so the encrypted diff is visible to git.
    Best-effort: returns False (and logs) if git is unavailable or the file is not tracked.
    """
    return _run_git_update_index("--no-skip-worktree", path)


def encrypt_secret_file(env_config: PartialEncryptionEnvironmentConfig) -> None:
    """
    Encrypt the secret file in-place using dotenvx.

    Args:
        env_config: Environment configuration

    Raises:
        PartialEncryptionError: If encryption fails
    """
    secret_file = Path(env_config.secret_file)

    if not secret_file.exists():
        return

    # Check if already encrypted
    if is_file_encrypted(secret_file):
        # Already encrypted (e.g. push run twice) — still lift any stale
        # skip-worktree protection so the encrypted diff is visible to git.
        _git_unskip_worktree(secret_file)
        return

    # Encrypt using dotenvx
    dotenvx = DotenvxWrapper()
    try:
        dotenvx.encrypt(secret_file)
    except DotenvxError as e:
        raise PartialEncryptionError.encrypt_failed(secret_file, e) from e

    # Re-enable git tracking now the file is encrypted again
    _git_unskip_worktree(secret_file)


def decrypt_secret_file(env_config: PartialEncryptionEnvironmentConfig) -> bool:
    """
    Decrypt the secret file in-place using dotenvx.

    Args:
        env_config: Environment configuration

    Returns:
        True if the file was successfully marked skip-worktree, False otherwise.

    Raises:
        PartialEncryptionError: If decryption fails
    """
    secret_file = Path(env_config.secret_file)

    if not secret_file.exists():
        raise PartialEncryptionError.file_not_found(secret_file)

    # Check if already decrypted
    if not is_file_encrypted(secret_file):
        # Already plaintext on disk — still protect it from accidental commit.
        return _git_skip_worktree(secret_file)

    # Decrypt using dotenvx
    dotenvx = DotenvxWrapper()
    try:
        dotenvx.decrypt(secret_file)
    except DotenvxError as e:
        raise PartialEncryptionError.decrypt_failed(secret_file, e) from e

    # Prevent accidental commit of the now-plaintext secret file.
    # git update-index --skip-worktree hides local changes from git add / git status
    # until encrypt_secret_file calls --no-skip-worktree after re-encryption.
    return _git_skip_worktree(secret_file)


def push_partial_encryption(
    env_config: PartialEncryptionEnvironmentConfig, *, check: bool = False
) -> dict[str, int | bool]:
    """
    Push operation: Encrypt secret file + combine with clear file.

    Steps:
    1. Encrypt .env.{env}.secret using dotenvx (in-place)
    2. Combine .env.{env}.clear + encrypted .secret → .env.{env}

    Args:
        env_config: Environment configuration
        check: When True, run as a dry run — do not encrypt and do not write the
            combined file. ``in_sync`` is True only when BOTH the combined file
            already matches the source files AND the secret file is encrypted. A
            plaintext secret file always reports out of sync (a real push would
            encrypt it), even if the combined file happens to match.

    Returns:
        Dict with stats: {"clear_lines": X, "secret_vars": Y, "in_sync": bool}

    Raises:
        PartialEncryptionError: If push operation fails
    """
    if check:
        # Dry run: never mutate the secret file or overwrite the combined file.
        stats = combine_files(env_config, write=False)
        # A real push would encrypt the secret file first, so an unencrypted secret
        # on disk means the project is NOT in a pushed state — regardless of whether
        # the combined-file text happens to line up.
        secret_file = Path(env_config.secret_file)
        if secret_file.exists() and not is_file_encrypted(secret_file):
            stats["in_sync"] = False
        return stats

    # Step 1: Encrypt secret file
    encrypt_secret_file(env_config)

    # Step 2: Combine files
    stats = combine_files(env_config)

    return stats


def _resolve_secrets_dir(env_config: PartialEncryptionEnvironmentConfig) -> Path:
    # Guard against an empty secrets_dir, which Path() would normalise to the
    # current working directory and silently process unrelated .env* files.
    raw = env_config.secrets_dir.strip()
    if not raw:
        raise PartialEncryptionError(
            f"secrets_dir must be set for secrets_only environment '{env_config.name}'"
        )
    secrets_dir = Path(raw)
    if not secrets_dir.exists() or not secrets_dir.is_dir():
        raise PartialEncryptionError(f"secrets_dir not found or not a directory: {secrets_dir}")
    return secrets_dir


def push_secrets_only(
    env_config: PartialEncryptionEnvironmentConfig, *, check: bool = False
) -> dict[str, int | bool]:
    """
    Secrets-only push: encrypt all matching files in secrets_dir in place.

    Does not touch any configs directory and does not produce a combined file.

    Note:
        ``pattern`` is applied via ``Path.glob`` and is non-recursive by default.
        To include nested subdirectories, use a recursive glob like ``**/.env*``.

    Args:
        env_config: Environment configuration with secrets_only=True
        check: When True, run as a dry run — do not encrypt anything. ``encrypted``
            then reports how many files *would* be encrypted.

    Returns:
        Dict with counts: {"encrypted": N, "already_encrypted": M, "in_sync": bool}

    Raises:
        PartialEncryptionError: If the secrets_dir does not exist or encryption fails
    """
    secrets_dir = _resolve_secrets_dir(env_config)

    files = sorted(secrets_dir.glob(env_config.pattern))
    encrypted = 0
    already_encrypted = 0
    dotenvx = DotenvxWrapper()

    for file in files:
        if not file.is_file():
            continue
        if file.name == _KEYS_FILENAME:
            # Never encrypt the dotenvx key file, even if it matches the pattern.
            continue
        if is_file_encrypted(file):
            if not check:
                # Already encrypted — lift any stale skip-worktree protection so
                # the encrypted diff is visible to git.
                _git_unskip_worktree(file)
            already_encrypted += 1
            continue
        if check:
            # Dry run: this plaintext file would be encrypted by a real push.
            encrypted += 1
            continue
        try:
            dotenvx.encrypt(file)
            encrypted += 1
        except DotenvxError as e:
            raise PartialEncryptionError.encrypt_failed(file, e) from e
        # Re-enable git tracking now the file is encrypted again.
        _git_unskip_worktree(file)

    return {
        "encrypted": encrypted,
        "already_encrypted": already_encrypted,
        "in_sync": encrypted == 0,
    }


def pull_secrets_only(env_config: PartialEncryptionEnvironmentConfig) -> dict[str, int]:
    """
    Secrets-only pull: decrypt all matching files in secrets_dir in place.

    Does not touch any configs directory.

    Note:
        ``pattern`` is applied via ``Path.glob`` and is non-recursive by default.
        To include nested subdirectories, use a recursive glob like ``**/.env*``.

    Args:
        env_config: Environment configuration with secrets_only=True

    Returns:
        Dict with counts: {"decrypted": N, "already_decrypted": M, "protected": P}
        where ``protected`` is the number of files successfully marked skip-worktree.

    Raises:
        PartialEncryptionError: If the secrets_dir does not exist or decryption fails
    """
    secrets_dir = _resolve_secrets_dir(env_config)

    files = sorted(secrets_dir.glob(env_config.pattern))
    decrypted = 0
    already_decrypted = 0
    protected = 0
    dotenvx = DotenvxWrapper()

    for file in files:
        if not file.is_file():
            continue
        if file.name == _KEYS_FILENAME:
            # Never decrypt the dotenvx key file, even if it matches the pattern.
            continue
        if not is_file_encrypted(file):
            # Already plaintext on disk — still protect it from accidental commit.
            if _git_skip_worktree(file):
                protected += 1
            already_decrypted += 1
            continue
        try:
            dotenvx.decrypt(file)
            decrypted += 1
        except DotenvxError as e:
            raise PartialEncryptionError.decrypt_failed(file, e) from e
        # Prevent accidental commit of the now-plaintext secret file until
        # push_secrets_only re-encrypts it and lifts the protection.
        if _git_skip_worktree(file):
            protected += 1

    return {"decrypted": decrypted, "already_decrypted": already_decrypted, "protected": protected}


class PullPartialResult(NamedTuple):
    """Outcome of a combine-mode pull for a single environment."""

    was_decrypted: bool  # True if the file was encrypted before this pull (i.e. got decrypted)
    protected: bool  # True if the file is now marked skip-worktree


def pull_partial_encryption(env_config: PartialEncryptionEnvironmentConfig) -> PullPartialResult:
    """
    Pull operation: Decrypt secret file for editing.

    Steps:
    1. Decrypt .env.{env}.secret in-place

    Args:
        env_config: Environment configuration

    Returns:
        PullPartialResult(was_decrypted, protected): whether the file was decrypted
        by this call, and whether it is now marked skip-worktree.

    Raises:
        PartialEncryptionError: If pull operation fails
    """
    secret_file = Path(env_config.secret_file)

    if not secret_file.exists():
        raise PartialEncryptionError.file_not_found(secret_file)

    was_encrypted = is_file_encrypted(secret_file)

    # Decrypt secret file
    protected = decrypt_secret_file(env_config)

    return PullPartialResult(was_decrypted=was_encrypted, protected=protected)
