"""Partial encryption functionality for envdrift.

This module implements a simple build pattern for partial encryption:
- Source files: .env.{env}.clear + .env.{env}.secret
- Generated file: .env.{env} (combined with warning header)
"""

from __future__ import annotations

import logging
import re
import subprocess  # nosec B404
from pathlib import Path
from typing import NamedTuple

from envdrift.config import PartialEncryptionEnvironmentConfig
from envdrift.env_files import _is_excluded_env_file
from envdrift.integrations.dotenvx import DotenvxError, DotenvxWrapper

logger = logging.getLogger(__name__)

# The dotenvx public-key header is a 4-line "#/" border/comment block:
#   #/---...[DOTENV_PUBLIC_KEY]---/   (top border, carries the marker)
#   #/ public-key encryption ... /   (inner comment)
#   #/ [how it works] ...         /   (inner comment)
#   #/---...---/                      (bottom border)
# combine_files strips ONLY this block from the secret file so the boilerplate
# does not clutter the combined artifact, while keeping the DOTENV_PUBLIC_KEY
# assignment and any legitimate user "#/" comment line intact. This mirrors the
# leading four "#/" lines of DotenvxWrapper.DOTENVX_HEADER_BLOCK_PATTERN
# (integrations/dotenvx.py) but stops before the public-key assignment so that
# line survives into the combined file.
_DOTENVX_HEADER_COMMENT_BLOCK = re.compile(
    r"#/-+\[DOTENV_PUBLIC_KEY\]-+/\n"
    r"#/[^\n]*/\n"
    r"#/[^\n]*/\n"
    r"#/-+/\n",
)

# Minimum inner width of the warning box. Long file paths expand the box beyond
# this so the right-hand border always stays aligned (see _build_warning_header).
_WARNING_BOX_MIN_WIDTH = 50

# dotenvx writes a public-key assignment into encrypted files. It is not a
# secret (public keys are public) so it must not be counted as a secret var.
_DOTENVX_PUBLIC_KEY_PREFIX = "DOTENV_PUBLIC_KEY"

# A dotenvx-encrypted value starts with this prefix; a SOPS-encrypted dotenv
# value starts with the AES-GCM marker. Detection keys off an actual assigned
# VALUE being ciphertext — never a header comment or a public-key line, both of
# which survive ``dotenvx decrypt`` while the values revert to plaintext (#352).
_DOTENVX_CIPHERTEXT_PREFIX = "encrypted:"
_SOPS_CIPHERTEXT_PREFIX = "ENC[AES256_GCM,"


def _build_warning_header(clear_file: str, secret_file: str) -> str:
    """Build the auto-generated-file warning box, sized to fit its content.

    The right-hand ``/`` border stays aligned regardless of how long the
    ``clear_file`` / ``secret_file`` paths are, because the box width grows to
    fit the longest line instead of using a fixed pad.
    """
    body = [
        "WARNING: AUTO-GENERATED FILE",
        "DO NOT EDIT THIS FILE DIRECTLY",
        "",
        "This file is generated by: envdrift push",
        "",
        "To make changes:",
        "  1. Run:  envdrift pull-partial (decrypts the .secret file)",
        f"  2. Edit: {clear_file}",
        f"  3. Edit: {secret_file}",
        "  4. Run:  envdrift push (re-encrypts .secret and regenerates this)",
    ]
    # Inner width includes the single leading space after "#/", hence +1.
    inner = max(_WARNING_BOX_MIN_WIDTH, max(len(line) for line in body) + 1)
    border = "#/" + "-" * inner + "/"
    lines = [border]
    lines.extend("#/ " + line.ljust(inner - 1) + "/" for line in body)
    lines.append(border)
    return "\n".join(lines) + "\n"


def _is_secret_var_line(line: str) -> bool:
    """Return True if ``line`` is a real secret variable assignment.

    Excludes comments and dotenvx's ``DOTENV_PUBLIC_KEY_*`` artifact so the
    reported secret-var count reflects only the actual secrets.
    """
    stripped = line.strip()
    if "=" not in stripped or stripped.startswith("#"):
        return False
    return not stripped.startswith(_DOTENVX_PUBLIC_KEY_PREFIX)


class PartialEncryptionError(Exception):
    """Partial encryption operation failed."""

    @classmethod
    def encrypt_failed(cls, path: Path, cause: Exception) -> PartialEncryptionError:
        """Create error for encryption failure."""
        return cls(f"Failed to encrypt {path}: {cause}")

    @classmethod
    def decrypt_failed(cls, path: Path, cause: Exception) -> PartialEncryptionError:
        """Create error for decryption failure."""
        return cls(f"Failed to decrypt {path}: {cause}")

    @classmethod
    def file_not_found(cls, path: Path) -> PartialEncryptionError:
        """Create error for missing file."""
        return cls(f"Secret file not found: {path}")


def _is_quote_wrapped(v: str) -> bool:
    """Return True if ``v`` is wrapped in a single matching pair of quotes.

    Recognises both ``"..."`` and ``'...'`` (the two quote styles dotenv/SOPS
    emit). A bare ``"`` or unbalanced quotes are not wrapped.
    """
    return len(v) >= 2 and v[0] in ('"', "'") and v[-1] == v[0]


def _unquote_value(value: str) -> str:
    """Strip surrounding whitespace and a single layer of matching quotes.

    SOPS emits ``KEY="ENC[AES256_GCM,...]"`` (quoted) while dotenvx emits an
    unquoted ``KEY=encrypted:...``; quoted empty placeholders appear as
    ``KEY=""`` / ``KEY=''``. Callers compare the returned bare value against the
    ciphertext prefixes or test it for emptiness, so both quote styles and
    surrounding whitespace must be removed first.
    """
    v = value.strip()
    if _is_quote_wrapped(v):
        v = v[1:-1].strip()
    return v


def _value_is_ciphertext(value: str) -> bool:
    """Return True if an assigned dotenv VALUE is genuine ciphertext."""
    v = _unquote_value(value)
    return v.startswith(_DOTENVX_CIPHERTEXT_PREFIX) or v.startswith(_SOPS_CIPHERTEXT_PREFIX)


def _line_has_plaintext_secret(line: str) -> bool:
    """Return True if a single ``.secret`` line is a PLAINTEXT secret assignment.

    Comments, blank lines, non-assignments and dotenvx's ``DOTENV_PUBLIC_KEY_*``
    artifact (a public key is not a secret) are filtered by ``_is_secret_var_line``
    and return False. Among real secret assignments, empty values
    (``KEY=`` / ``KEY=""`` / ``KEY=''``) carry no secret to leak, and ciphertext
    values are already encrypted; only a non-empty plaintext value returns True.
    """
    if not _is_secret_var_line(line):
        return False
    _, _, value = line.strip().partition("=")
    # Empty assignment (KEY=, KEY="", KEY='') carries no secret to leak.
    return bool(_unquote_value(value)) and not _value_is_ciphertext(value)


def has_plaintext_secret_value(file_path: Path) -> bool:
    """Return True if the file still holds at least one PLAINTEXT secret value.

    A "plaintext secret value" is a real variable assignment whose value is not
    ciphertext — excluding comments, blank lines and dotenvx's
    ``DOTENV_PUBLIC_KEY_*`` artifact (a public key is not a secret).

    This distinguishes a MIXED-STATE file (some values already ``encrypted:``,
    at least one freshly-added plaintext value) from a fully-encrypted one.
    ``is_file_encrypted`` returns True on the *first* ciphertext value, so a
    mixed file looks "already encrypted" to it and the push path would early-
    return — shipping the new plaintext secret verbatim into the committed
    ``.secret`` file and the generated combined file. Callers force a re-encrypt
    when this returns True (``dotenvx encrypt`` is idempotent: it re-encrypts
    only the plaintext values and leaves existing ciphertext untouched).
    """
    if not file_path.exists():
        return False

    # errors="replace" for the same reason as is_file_encrypted: callers have no
    # surrounding handler, and a ciphertext marker is ASCII so replacement chars
    # cannot make a plaintext value look like ciphertext.
    content = file_path.read_text(encoding="utf-8", errors="replace")

    return any(_line_has_plaintext_secret(raw_line) for raw_line in content.splitlines())


def is_file_encrypted(file_path: Path) -> bool:
    """Return True only when the file actually contains CIPHERTEXT.

    True requires at least one assigned VALUE to be genuinely encrypted
    (dotenvx ``encrypted:`` or SOPS ``ENC[AES256_GCM,``), or a real SOPS
    metadata block.

    The #352 bug this fixes: the old check was
    ``"encrypted:" in content or "DOTENV_VAULT" in content``, so a PLAINTEXT
    value that merely *contained* the substring ``encrypted:`` (e.g.
    ``NOTE=... the secret is stored encrypted: see docs``) false-positived as
    "already encrypted". ``encrypt_secret_file`` then early-returned and the
    real secrets in that file were committed in cleartext. Anchoring detection
    to a VALUE that *starts with* a ciphertext prefix removes that false
    positive.

    Related safety property (a forward-guard, not the #352 bug itself): a
    dotenvx file that has been DECRYPTED keeps its ``DOTENV_PUBLIC_KEY_*`` line
    and header comment while its values revert to plaintext. Those markers must
    not count as encrypted either, so re-encryption (lock -> pull -> lock) still
    fires. The old substring check already returned False for such files (they
    hold neither substring); the value-scan preserves that.

    Args:
        file_path: Path to check

    Returns:
        True if the file holds at least one encrypted value or a SOPS metadata block.
    """
    if not file_path.exists():
        return False

    # errors="replace": a non-UTF-8 file (e.g. a Latin-1 byte in a value) must not
    # raise UnicodeDecodeError here — is_file_encrypted is called from the push/
    # pull/encrypt paths with no surrounding handler, so an exception would abort
    # the whole operation. A real dotenvx/SOPS ciphertext marker is ASCII, so
    # replacement characters cannot turn a plaintext file into a false positive.
    content = file_path.read_text(encoding="utf-8", errors="replace")

    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        _, _, value = line.partition("=")
        if _value_is_ciphertext(value):
            return True

    # Real SOPS metadata block: the trailer carries sops_version alongside an
    # encrypted MAC value. Both present means it is a genuine SOPS file even if
    # the assignment scan above did not trip (defensive belt-and-suspenders).
    return "sops_version" in content and _SOPS_CIPHERTEXT_PREFIX in content


def _is_fully_encrypted(file_path: Path) -> bool:
    """Return True only when the file is FULLY encrypted (push would no-op).

    Fully encrypted means ciphertext is present AND no leftover plaintext secret
    value remains. ``is_file_encrypted`` trips on the *first* ciphertext value,
    so a MIXED-STATE file (some values encrypted, one freshly-added plaintext)
    looks "encrypted" to it alone; pairing it with ``has_plaintext_secret_value``
    distinguishes a file a real push would re-encrypt from one it would skip.
    The encrypt paths and the dry-run ``--check`` sync test share this predicate
    so they agree on what "already pushed" means.
    """
    return is_file_encrypted(file_path) and not has_plaintext_secret_value(file_path)


def combine_files(
    env_config: PartialEncryptionEnvironmentConfig, *, write: bool = True
) -> dict[str, int | bool]:
    """
    Combine clear and encrypted secret files into a single combined file.

    Process:
        1. Read .env.{env}.clear (cleartext vars)
        2. Read .env.{env}.secret (encrypted vars)
        3. Combine with warning header → .env.{env}

    Args:
        env_config: Environment configuration
        write: When True (default) the combined file is written to disk. When
            False this is a dry run that computes the would-be content and
            reports whether it matches the existing combined file, without
            touching disk. Used by ``envdrift push --check``.

    Returns:
        Dict with counts: {"clear_lines": X, "secret_vars": Y, "in_sync": bool}.
        ``in_sync`` reports whether the on-disk combined file already matches the
        freshly-computed content (always True after a real write).

    Raises:
        PartialEncryptionError: If operation fails
    """
    clear_file = Path(env_config.clear_file)
    secret_file = Path(env_config.secret_file)
    combined_file = Path(env_config.combined_file)

    # Read files
    clear_lines = []
    if clear_file.exists():
        clear_lines = clear_file.read_text(encoding="utf-8").splitlines()

    secret_lines = []
    secret_file_content = None
    if secret_file.exists():
        secret_file_content = secret_file.read_text(encoding="utf-8")
        secret_lines = secret_file_content.splitlines()

    # Build combined content with warning header
    warning = _build_warning_header(env_config.clear_file, env_config.secret_file)

    combined_lines = warning.splitlines()
    combined_lines.append("")

    # Add clear section
    if clear_lines:
        combined_lines.append(f"# From {env_config.clear_file}")
        combined_lines.extend(clear_lines)
        combined_lines.append("")

    # Add encrypted secret section
    if secret_lines and secret_file_content is not None:
        # Strip ONLY the dotenvx public-key header block (the 4-line "#/"
        # border/comment boilerplate) to avoid clutter. Matching the precise
        # block — rather than every line starting with "#/" — preserves a
        # legitimate user comment such as "#/ note about this key" that would
        # otherwise be silently dropped from the generated combined file.
        stripped_text = _DOTENVX_HEADER_COMMENT_BLOCK.sub("", secret_file_content)
        secret_content = stripped_text.splitlines()
        combined_lines.append(f"# From {env_config.secret_file} (encrypted)")
        combined_lines.extend(secret_content)

    new_content = "\n".join(combined_lines) + "\n"

    existing = combined_file.read_text(encoding="utf-8") if combined_file.exists() else None
    in_sync = existing == new_content

    if write:
        combined_file.write_text(new_content, encoding="utf-8")
        in_sync = True

    # Count real secret variables (excludes comments and dotenvx public-key line)
    secret_var_count = sum(1 for line in secret_lines if _is_secret_var_line(line))

    return {
        "clear_lines": len(clear_lines),
        "secret_vars": secret_var_count,
        "in_sync": in_sync,
    }


def _run_git_update_index(flag: str, path: Path) -> bool:
    """Run ``git update-index <flag> <path>`` and report whether it succeeded.

    Returns True only when git exits 0. A non-zero exit (e.g. the file is not
    tracked) is logged as a warning rather than failing silently; git being
    unavailable is logged at debug level. Either way the caller gets False so it
    can avoid claiming protection that was never applied.
    """
    try:
        result = subprocess.run(  # nosec B603, B607
            ["git", "update-index", flag, str(path)],
            capture_output=True,
            timeout=10,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as exc:
        logger.debug("git update-index %s not applied to %s: %s", flag, path, exc)
        return False
    if result.returncode != 0:
        stderr = result.stderr
        if isinstance(stderr, (bytes, bytearray)):
            stderr = stderr.decode(errors="replace")
        logger.warning(
            "git update-index %s failed for %s (exit %s): %s",
            flag,
            path,
            result.returncode,
            (stderr or "").strip(),
        )
        return False
    return True


def _git_skip_worktree(path: Path) -> bool:
    """Mark path as skip-worktree so git ignores local changes while the file is decrypted.

    This prevents `git add .` from staging a plaintext .secret file after pull-partial.
    Best-effort: returns False (and logs) if git is unavailable or the file is not tracked.
    """
    return _run_git_update_index("--skip-worktree", path)


def _git_unskip_worktree(path: Path) -> bool:
    """Unmark path from skip-worktree so git can track the re-encrypted version.

    Called after encrypt_secret_file so the encrypted diff is visible to git.
    Best-effort: returns False (and logs) if git is unavailable or the file is not tracked.
    """
    return _run_git_update_index("--no-skip-worktree", path)


def encrypt_secret_file(env_config: PartialEncryptionEnvironmentConfig) -> None:
    """
    Encrypt the secret file in-place using dotenvx.

    Args:
        env_config: Environment configuration

    Raises:
        PartialEncryptionError: If encryption fails
    """
    secret_file = Path(env_config.secret_file)

    if not secret_file.exists():
        return

    # Skip re-encryption ONLY when the file is FULLY encrypted: it holds
    # ciphertext AND no leftover plaintext secret value. A MIXED file (some
    # values already encrypted, one freshly-added plaintext) must still be
    # re-encrypted — otherwise the new plaintext secret leaks into the committed
    # .secret file and the combined file. is_file_encrypted() returns True on
    # the first ciphertext value, so it alone cannot tell the two apart.
    if _is_fully_encrypted(secret_file):
        # Already fully encrypted (e.g. push run twice) — still lift any stale
        # skip-worktree protection so the encrypted diff is visible to git.
        _git_unskip_worktree(secret_file)
        return

    # Encrypt using dotenvx (idempotent: re-encrypts only the plaintext values,
    # leaving any already-encrypted values untouched).
    dotenvx = DotenvxWrapper()
    try:
        dotenvx.encrypt(secret_file)
    except DotenvxError as e:
        raise PartialEncryptionError.encrypt_failed(secret_file, e) from e

    # Re-enable git tracking now the file is encrypted again
    _git_unskip_worktree(secret_file)


def decrypt_secret_file(env_config: PartialEncryptionEnvironmentConfig) -> bool:
    """
    Decrypt the secret file in-place using dotenvx.

    Args:
        env_config: Environment configuration

    Returns:
        True if the file was successfully marked skip-worktree, False otherwise.

    Raises:
        PartialEncryptionError: If decryption fails
    """
    secret_file = Path(env_config.secret_file)

    if not secret_file.exists():
        raise PartialEncryptionError.file_not_found(secret_file)

    # Check if already decrypted
    if not is_file_encrypted(secret_file):
        # Already plaintext on disk — still protect it from accidental commit.
        return _git_skip_worktree(secret_file)

    # Decrypt using dotenvx
    dotenvx = DotenvxWrapper()
    try:
        dotenvx.decrypt(secret_file)
    except DotenvxError as e:
        raise PartialEncryptionError.decrypt_failed(secret_file, e) from e

    # Prevent accidental commit of the now-plaintext secret file.
    # git update-index --skip-worktree hides local changes from git add / git status
    # until encrypt_secret_file calls --no-skip-worktree after re-encryption.
    return _git_skip_worktree(secret_file)


def push_partial_encryption(
    env_config: PartialEncryptionEnvironmentConfig, *, check: bool = False
) -> dict[str, int | bool]:
    """
    Push operation: Encrypt secret file + combine with clear file.

    Steps:
    1. Encrypt .env.{env}.secret using dotenvx (in-place)
    2. Combine .env.{env}.clear + encrypted .secret → .env.{env}

    Args:
        env_config: Environment configuration
        check: When True, run as a dry run — do not encrypt and do not write the
            combined file. ``in_sync`` is True only when BOTH the combined file
            already matches the source files AND the secret file is FULLY
            encrypted. A plaintext or mixed-state secret file (a freshly-added
            plaintext value alongside existing ciphertext) always reports out of
            sync — a real push would re-encrypt it — even if the combined file
            happens to match.

    Returns:
        Dict with stats: {"clear_lines": X, "secret_vars": Y, "in_sync": bool}

    Raises:
        PartialEncryptionError: If push operation fails
    """
    if check:
        # Dry run: never mutate the secret file or overwrite the combined file.
        stats = combine_files(env_config, write=False)
        # A real push would re-encrypt the secret file first, so a secret that is
        # not fully encrypted on disk means the project is NOT in a pushed state —
        # regardless of whether the combined-file text happens to line up. This
        # mirrors the encrypt-path skip guard (is_file_encrypted AND no leftover
        # plaintext secret): a mixed-state file (some ciphertext, one freshly
        # added plaintext value) trips is_file_encrypted but would still be
        # re-encrypted, so it must report out of sync.
        secret_file = Path(env_config.secret_file)
        if secret_file.exists() and not _is_fully_encrypted(secret_file):
            stats["in_sync"] = False
        return stats

    # Step 1: Encrypt secret file
    encrypt_secret_file(env_config)

    # Step 2: Combine files
    stats = combine_files(env_config)

    return stats


def _resolve_secrets_dir(env_config: PartialEncryptionEnvironmentConfig) -> Path:
    # Guard against an empty secrets_dir, which Path() would normalise to the
    # current working directory and silently process unrelated .env* files.
    raw = env_config.secrets_dir.strip()
    if not raw:
        raise PartialEncryptionError(
            f"secrets_dir must be set for secrets_only environment '{env_config.name}'"
        )
    secrets_dir = Path(raw)
    if not secrets_dir.exists() or not secrets_dir.is_dir():
        raise PartialEncryptionError(f"secrets_dir not found or not a directory: {secrets_dir}")
    return secrets_dir


def push_secrets_only(
    env_config: PartialEncryptionEnvironmentConfig, *, check: bool = False
) -> dict[str, int | bool]:
    """
    Secrets-only push: encrypt all matching files in secrets_dir in place.

    Does not touch any configs directory and does not produce a combined file.

    Note:
        ``pattern`` is applied via ``Path.glob`` and is non-recursive by default.
        To include nested subdirectories, use a recursive glob like ``**/.env*``.

    Args:
        env_config: Environment configuration with secrets_only=True
        check: When True, run as a dry run — do not encrypt anything. ``encrypted``
            then reports how many files *would* be encrypted.

    Returns:
        Dict with counts: {"encrypted": N, "already_encrypted": M, "in_sync": bool}

    Raises:
        PartialEncryptionError: If the secrets_dir does not exist or encryption fails
    """
    secrets_dir = _resolve_secrets_dir(env_config)

    files = sorted(secrets_dir.glob(env_config.pattern))
    encrypted = 0
    already_encrypted = 0
    dotenvx = DotenvxWrapper()

    for file in files:
        if not _is_pushable_secret_file(file):
            continue
        if _encrypt_secrets_only_file(dotenvx, file, check=check):
            encrypted += 1
        else:
            already_encrypted += 1

    return {
        "encrypted": encrypted,
        "already_encrypted": already_encrypted,
        "in_sync": encrypted == 0,
    }


def _is_pushable_secret_file(file: Path) -> bool:
    """Return True if ``file`` is a real secret file eligible for encryption.

    Skips non-files and companion files (.example/.sample/.template) or the
    dotenvx key file (.keys), even if they match the glob pattern (#358).
    """
    return file.is_file() and not _is_excluded_env_file(file.name)


def _encrypt_secrets_only_file(dotenvx: DotenvxWrapper, file: Path, *, check: bool) -> bool:
    """Encrypt a single secrets-only file in place; return True if it was (re)encrypted.

    A file counts as "already encrypted" only when it is FULLY encrypted:
    ciphertext present AND no leftover plaintext secret value. A MIXED file
    (some values encrypted, one freshly-added plaintext) must be re-encrypted,
    or the new plaintext secret ships verbatim. ``is_file_encrypted`` trips on
    the first ciphertext value, so it alone treats a mixed file as done —
    ``has_plaintext_secret_value`` catches the leak.

    Returns False (already-encrypted) without touching ``dotenvx`` when the file
    is fully encrypted. In ``check`` mode no file is modified.
    """
    if _is_fully_encrypted(file):
        if not check:
            # Already fully encrypted — lift any stale skip-worktree protection
            # so the encrypted diff is visible to git.
            _git_unskip_worktree(file)
        return False
    if check:
        # Dry run: this plaintext / mixed file would be encrypted by a real push.
        return True
    try:
        dotenvx.encrypt(file)
    except DotenvxError as e:
        raise PartialEncryptionError.encrypt_failed(file, e) from e
    # Re-enable git tracking now the file is encrypted again.
    _git_unskip_worktree(file)
    return True


def pull_secrets_only(env_config: PartialEncryptionEnvironmentConfig) -> dict[str, int]:
    """
    Secrets-only pull: decrypt all matching files in secrets_dir in place.

    Does not touch any configs directory.

    Note:
        ``pattern`` is applied via ``Path.glob`` and is non-recursive by default.
        To include nested subdirectories, use a recursive glob like ``**/.env*``.

    Args:
        env_config: Environment configuration with secrets_only=True

    Returns:
        Dict with counts: {"decrypted": N, "already_decrypted": M, "protected": P}
        where ``protected`` is the number of files successfully marked skip-worktree.

    Raises:
        PartialEncryptionError: If the secrets_dir does not exist or decryption fails
    """
    secrets_dir = _resolve_secrets_dir(env_config)

    files = sorted(secrets_dir.glob(env_config.pattern))
    decrypted = 0
    already_decrypted = 0
    protected = 0
    dotenvx = DotenvxWrapper()

    for file in files:
        if not file.is_file():
            continue
        if _is_excluded_env_file(file.name):
            # Never decrypt companion files (.example/.sample/.template) or the
            # dotenvx key file (.keys), even if they match the glob pattern (#358).
            continue
        if not is_file_encrypted(file):
            # Already plaintext on disk — still protect it from accidental commit.
            if _git_skip_worktree(file):
                protected += 1
            already_decrypted += 1
            continue
        try:
            dotenvx.decrypt(file)
            decrypted += 1
        except DotenvxError as e:
            raise PartialEncryptionError.decrypt_failed(file, e) from e
        # Prevent accidental commit of the now-plaintext secret file until
        # push_secrets_only re-encrypts it and lifts the protection.
        if _git_skip_worktree(file):
            protected += 1

    return {"decrypted": decrypted, "already_decrypted": already_decrypted, "protected": protected}


class PullPartialResult(NamedTuple):
    """Outcome of a combine-mode pull for a single environment."""

    was_decrypted: bool  # True if the file was encrypted before this pull (i.e. got decrypted)
    protected: bool  # True if the file is now marked skip-worktree


def pull_partial_encryption(env_config: PartialEncryptionEnvironmentConfig) -> PullPartialResult:
    """
    Pull operation: Decrypt secret file for editing.

    Steps:
    1. Decrypt .env.{env}.secret in-place

    Args:
        env_config: Environment configuration

    Returns:
        PullPartialResult(was_decrypted, protected): whether the file was decrypted
        by this call, and whether it is now marked skip-worktree.

    Raises:
        PartialEncryptionError: If pull operation fails
    """
    secret_file = Path(env_config.secret_file)

    if not secret_file.exists():
        raise PartialEncryptionError.file_not_found(secret_file)

    was_encrypted = is_file_encrypted(secret_file)

    # Decrypt secret file
    protected = decrypt_secret_file(env_config)

    return PullPartialResult(was_decrypted=was_encrypted, protected=protected)
